sudo: required
services:
  - docker

before_install:
  - docker build -t ubermensch01/multiple-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run ubermensch01/multiple-docker npm test -- --coverage

after_success:
  - docker build -t ubermensch01/multi-client ./client
  - docker build -t ubermensch01/multi-nginx ./nginx
  - docker build -t ubermensch01/multi-server ./server
  - docker build -t ubermensch01/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all that to Docker hub
  - docker push ubermensch01/multi-client
  - docker push ubermensch01/multi-nginx
  - docker push ubermensch01/multi-server
  - docker push ubermensch01/multi-worker


deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-826507567886
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY